#! /usr/bin/env python
from __future__ import division

import rospy
from geometry_msgs.msg import Twist
from std_msgs.msg import Int16MultiArray

from mecanum_drive import controller

class ControllerNode:

    def __init__(self):
        self.controller = controller.Controller()
        self.linearXVelocity = 0.0
        self.linearYVelocity = 0.0
        self.angularVelocity = 0.0
        self.wheels_to_send = Int16MultiArray()

    def main(self):                                        
        self.wheelPub = rospy.Publisher('wheels_desired_rate',
                                        Int16MultiArray, queue_size=1)
                                        
        rospy.init_node('mecanum_drive_controller')
        self.nodeName = rospy.get_name()
        rospy.loginfo("{0} started".format(self.nodeName))

        rospy.Subscriber("cmd_vel", Twist, self.twistCallback)

        self.ticksPerMeter = float(rospy.get_param('~ticks_per_meter'))
        self.wheelSeparation = float(rospy.get_param('~wheel_separation'))
        self.wheelSeparationLength = float(rospy.get_param('~wheel_separation_length'))
        self.maxMotorSpeed = int(rospy.get_param('~max_motor_speed'))
        self.rate = float(rospy.get_param('~rate', 10.0))
        self.timeout = float(rospy.get_param('~timeout', 0.2))

        self.controller.setWheelSeparation(self.wheelSeparation)
        self.controller.setWheelSeparationLength(self.wheelSeparationLength)
        self.controller.setTicksPerMeter(self.ticksPerMeter)
        self.controller.setMaxMotorSpeed(self.maxMotorSpeed)

        rate = rospy.Rate(self.rate)
        self.lastTwistTime = rospy.get_time()
        while not rospy.is_shutdown():
            self.publish()
            rate.sleep()

    def publish(self):
        if rospy.get_time() - self.lastTwistTime < self.timeout:
            speeds = self.controller.getSpeeds(self.linearXVelocity,self.linearYVelocity,
                                               self.angularVelocity)

            self.wheels_to_send.data = [int(speeds.frontLeft), int(speeds.frontRight), int(speeds.rearLeft), int(speeds.rearRight)]
            self.wheelPub.publish(self.wheels_to_send)
        else:
            self.wheels_to_send.data = [0, 0, 0, 0]
            self.wheelPub.publish(self.wheels_to_send)

    def twistCallback(self, twist):
        self.linearXVelocity = twist.linear.x
        self.linearYVelocity = twist.linear.y
        self.angularVelocity = twist.angular.z
        # print("%d,%d" % (self.linearVelocity, self.angularVelocity))
        self.lastTwistTime = rospy.get_time()

if __name__ == '__main__':
    try:
        node = ControllerNode()
        node.main()
    except rospy.ROSInterruptException:
        pass
